---
name: Molecule test & Ansible-Galaxy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: 'leadlineit.leadlineit'

jobs:
  lint:
    name: Linting the syntax
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'leadlineit.leadlineit'

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip install yamllint

      - name: Lint code
        run: |
          yamllint .

  release:
    name: Release
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'leadlineit.leadlineit'

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible-base

      - name: Trigger a new import on Ansible Galaxy
        run: |
          ansible-galaxy import \
          --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} \
          $(echo ${{ github.repository }} | cut -d/ -f1) \
          $(echo ${{ github.repository }} | cut -d- -f3)
